#!/usr/bin/env python3
import sys
from io import StringIO
import glob
from pylint.lint import Run



for source in ['ldc/lisa/noise/noise.py',
               'ldc/common/constants/cosmology.py']+glob.glob("ldc/waveform/waveform/*.py"):
    stdout = sys.stdout
    sys.stdout = StringIO()

    #Run(['--errors-only', 'ldc/lisa/noise/noise.py', '--rcfile=.pylintrc']) 
    out = Run([source, '--rcfile=.pylintrc'], exit=False) 
    out = sys.stdout.getvalue()
    sys.stdout.close()
    sys.stdout = stdout
    
    print (out)

    score = float(out.split("Your code has been rated at ")[-1].split("/")[0])
    print(score)
    if score<5:
        exit(-1)
