#!/usr/bin/env python3
from astropy import units as u
import ldc.io.hdf5 as hdf5io
import ldc.io.npz as npzio
import ldc.io.txt as txtio
import os

if __name__ == "__main__":

    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('--input-file', type=str, default="",
                        help="Input hdf5 file without units")
    parser.add_argument('--output-dir', type=str, default="",
                        help="Output directory")
    parser.add_argument('--blind', action='store_true',
                        help="Blind data set")
    args = parser.parse_args()

    cats = ["sky/vgb/cat", "sky/dgb/cat", "sky/igb/cat", "sky/mbhb/cat"]
    tdi = ["obs/tdi"]

    if not args.blind:
        for c in cats:
            arr, attr = hdf5io.load_array(args.input_file, name=c)
            out = os.path.join(args.output_dir, c.replace("/", "_")+".txt.gz")
            txtio.save_array(out, arr)

    for c in tdi:
        arr, attr = hdf5io.load_array(args.input_file, name=c)
        out = os.path.join(args.output_dir, c.replace("/", "_")+".txt.gz")
        txtio.save_array(out, arr)

        
